version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: eduardomdcup/dynamicity_unm:latest
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOSTNAME=db
      - DB_PORT=5432
      - SECRET_KEY=secret_key_dynamicity
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=* localhost 127.0.0.1 [::1]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    restart: on-failure