# Generated by Django 4.1.9 on 2023-05-12 18:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dynamiCITY_app', '0004_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='county',
            name='pop',
        ),
        migrations.CreateModel(
            name='Area_property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('property_name', models.CharField(max_length=100)),
                ('property_value', models.CharField(max_length=100)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamiCITY_app.area')),
            ],
            options={
                'verbose_name_plural': 'Area_properties',
            },
        ),
    ]
