# Generated by Django 4.1.9 on 2023-05-19 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamiCITY_app', '0005_remove_county_pop_area_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='pop',
        ),
    ]
